ignore:
  # False positive: https://github.com/anchore/grype/issues/558
  - vulnerability: CVE-2015-5237

  # False positive: https://github.com/anchore/grype/issues/558
  - vulnerability: CVE-2021-22570