name: E2E Tests
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - "docs/**"
      
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region us-east-1

      - name: Install and Configure Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          curl -fsSL https://get.pulumi.com | sh
          pulumi login

      - name: Generate SSH Key
        env:
          SSH_KEY_PATH: ${{ secrets.SSH_KEY_PATH }}
          SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}
          SSH_KEY: ${{ env.SSH_KEY_PATH }}${{ env.SSH_KEY_FILE }}
        run: |
          mkdir -p "$SSH_KEY_PATH"
          ssh-keygen -t rsa -b 4096 -f "$SSH_KEY" -N ""

      - name: Add SSH Key Filepath to Config File
        env:
          SSH_KEY_PATH: ${{ secrets.SSH_KEY_PATH }}
          SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}
          SSH_KEY: ${{ env.SSH_KEY_PATH }}${{ env.SSH_KEY_FILE }}
        run: yq ".sshKeyPath = \"$SSH_KEY\"" -i config.yaml

      - name: Build Binary
        run: make build

      - name: Provision Infrastructure
        continue-on-error: true
        run: make up

      - name: Test Cluster Access
        continue-on-error: true
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          kubectl get nodes --kubeconfig=./kubeconfig

      - name: Teardown Infrastructure
        run: make down
