name: E2E Tests
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - "docs/**"
      
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Test aws cli installation
        run: aws --help

      
