name: Unit Tests
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - "docs/**"
      
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Run Unit Tests
        run: |
          make unit-test